import "@/styles/app.scss"

export const metadata = {
  title: 'Foody Delivery - Rastreamento de Pedidos',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <head></head>
      <body>{children}</body>
    </html>
  )
}
