import '@/styles/index.scss';
import { AuthProvider } from '@/contexts/AuthContext';

export const metadata = {
  title: 'Foody Delivery - Rastreamento de Pedidos',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <head>
      </head>
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}